### PR TITLE
I want to add my PR. May you confirm it please? 

### LINKED ISSUE #4: Set Up the  vagrant
You need to Create Vagrantfile includes:
1. Memory.
2. Sherd library.
3. network setting.

### PR DESCRIPTION
**Pull request by ronityosefia**
fixes #4

### CODE REVIEW

**Review by lmilbaum — CHANGES_REQUESTED** [review]
This PR has conflicts with another one which was probably merged. Rebase this one or close it.

**Comment by BarBenNaim** [comment]
We want to merge it

**Comment by lmilbaum** [comment]
> We want to merge it

Than please rebase it. It has conflicts.
BTW, PR title should indicate the code contribution content. Not the action that should be done.

**Comment by BarBenNaim** [comment]
> > We want to merge it
> 
> Than please rebase it. It has conflicts.
> BTW, PR title should indicate the code contribution content. Not the action that should be done.

Who should do it?
Ronit should. 
Who sent the request? Or everyone?
Which request? I am not following

**Pull request closed without merging**
