### PR TITLE
2nd PR from Rom: creating Django env & Flake8

### LINKED ISSUE #4: Set Up the  vagrant
You need to Create Vagrantfile includes:
1. Memory.
2. Sherd library.
3. network setting.

### LINKED ISSUE #5: Create setup.sh
includes:
1. install pipenv
2. runs erver

### LINKED ISSUE #6: flake8
create flake8 file  includes the path .github/workflows

### LINKED ISSUE #7: Django
pipenv
python 3
django

### LINKED ISSUE #13: Home page is not shown on vagrant up
Running vagrant file
vagrant up
Vagrant is up
curl 127.0.0.1:8080
Page is not up.

I think Vagrant file should include the 
config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"

### PR DESCRIPTION
**Pull request by RomTamam**
Hi please review and approve this PR.
This PR contains Django creation & Flake 8 configuration.

Thanks

### CODE REVIEW

**Comment by ravidbro** [comment]
IMO, it's too much to fix all these issues with one commit

**Comment by BarBenNaim** [comment]
We will learn for next time, is it possible to move forward?
We want to move forward with the project, we are so behind.

**Comment by ravidbro** [comment]
I will let @sim to decide about that.

It quite simple to split the last commit in a branch into a few commits:
1. git reset HEAD^    (This will remove the commit and will put all the files as unstaged)
2. git add file1 file2 ... (The files that you want in the first commit)
3. git commit -m "message for the commit of file1 file2"

Repeat on steps 2-3 until you don't see any more files in 'git status'

4. git push -f origin <branch_name>

**Comment by BarBenNaim** [comment]
OK, we will do it!
thanks for the instructions it's very helpful

**Comment by BarBenNaim** [comment]
Rom will send tomorrow the PR's

**Pull request closed without merging**
