### PR TITLE
pytest yml

### LINKED ISSUE #85: PyTest yml for PyTest via GitHub

### PR DESCRIPTION
**Pull request by BarBenNaim**
fixes #85

### CODE REVIEW

**Comment by simzacks** [comment]
@Yarboa  - it looks like this code is good and it shows a problem with the actual tests. My thought is to approve this PR and ask them to fix the tests. If you agree, please merge.

**Comment by BarBenNaim** [comment]
> @Yarboa - it looks like this code is good and it shows a problem with the actual tests. My thought is to approve this PR and ask them to fix the tests. If you agree, please merge.

the file good, but the test failed.
I think you need to merge it.
and we deal with the test later.

**Comment by Yarboa** [comment]
> > @Yarboa - it looks like this code is good and it shows a problem with the actual tests. My thought is to approve this PR and ask them to fix the tests. If you agree, please merge.

The test itself should be changed, since the jobs are static, from time to time jobs should change,
Please open an Issue
> 
> the file good, but the test failed.
> I think you need to merge it.
> and we deal with the test later.

**Comment by Yarboa** [comment]
> @Yarboa - it looks like this code is good and it shows a problem with the actual tests. My thought is to approve this PR and ask them to fix the tests. If you agree, please merge.

ACK

**Pull request merged**
